---
- hosts: my_tcpconn
  vars:
    server_port: 5000
    server_host: 10.9.5.10
  remote_user: root
  gather_facts: no
  tasks:
  - name: ensure python-pip python-devel unzip is present
    yum: name={{item}} state=present
    with_items:
      - python-pip
      - python-devel
      - unzip
      - gcc
  - name: unzip file
    unarchive: src=master.zip dest=/opt/

  - name: install psutil
    pip: name=psutil extra_args='-i https://mirrors.aliyun.com/pypi/simple/'

  - name: change config file
    shell: sed -i '/SERVER/d' /opt/my_tcpconn-master/config.py && echo -e "SERVER_HOST = '{{server_host}}'\nSERVER_PORT = {{server_port}}" >> /opt/my_tcpconn-master/config.py

  - name: run a test
    shell: cd /opt/my_tcpconn-master/; python client.py
    tags:
      - test

