---
- hosts: my_tcpconn
  vars:
    server_port: 5000
    server_host: 172.20.12.106
  remote_user: root
  gather_facts: no
  tasks:
  - name: ensure python-pip python-devel unzip is present
    yum: 
      name: ['python3-pip', 'python3-devel', 'gcc']

  - name: git clone
    git: 
      repo: 'https://github.com/4admin2root/my_tcpconn.git'
      dest: /opt/my_tcpconn
      version: python3

  - name: install psutil
    pip: 
      requirements: /opt/my_tcpconn/requirements_client.txt
      extra_args: '-i https://mirrors.aliyun.com/pypi/simple/'
      executable: pip3

  - name: change config file
    shell: sed -i '/SERVER/d' /opt/my_tcpconn/config.py && echo -e "SERVER_HOST = '{{server_host}}'\nSERVER_PORT = {{server_port}}" >> /opt/my_tcpconn/config.py

  - name: run a test
    shell: cd /opt/my_tcpconn/; nohup python3 client.py &
    tags:
      - test
